[package]
name = "rustyray-math"
version = "0.1.0"
edition = "2021"

[dependencies]
rustyray-ffi = { version = "*", path = "../rustyray-ffi" }
serde = { version = "1.0.217", features = ["derive"] }

[features]
default = ["serde"]
serde = []
