[package]
name = "rustyray"
description = "Safe bindings for Raylib done in a rust fashion."
version = "0.1.0"
edition = "2021"
repository = "https://github.com/wizzymore/rustyray"
license-file.workspace = true

[dependencies]
rustyray-ffi = { version = "0.1.0", path = "../rustyray-ffi" }
serde = { version = "1.0.217", features = ["derive"] }

[dev-dependencies]
rand = "0.9.0"

[[example]]
name = "window"

[[example]]
name = "bunnymark"

[features]
default = ["serde"]
serde = []
