[package]
name = "rustyray"
description = "Safe bindings for Raylib done in a rust fashion."
version = "0.1.0"
edition = "2021"
repository = "https://github.com/wizzymore/rustyray"

[dependencies]
rand = "0.9.0"
rustyray-ffi = { version = "*", path = "../rustyray-ffi" }
rustyray-math = { version = "*", path = "../rustyray-math" }
serde = { version = "1.0.217", features = ["derive"] }

[[example]]
name = "window"

[[example]]
name = "bunnymark"

[features]
default = ["serde"]
serde = []
