[package]
name = "rustyray"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
rustyray-sys = { path = "../rustyray-sys" }
serde = { version = "1.0.217", features = ["derive"] }

[[example]]
name = "window"

[[example]]
name = "bunnymark"

[features]
default = ["serde"]
serde = []
