name: CI

on:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{runner.os}}-cargo-build-${{ hashFiles('**/Cargo.toml') }}
      - name: Setup git submodules
        run: git submodule init; git submodule update
      - name: Install alsa, udev, glfw3, sdl, and wayland
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libglfw3-dev libwayland-dev libsdl2-dev
      - name: Run doc tests
        run: cargo test --doc --verbose
      - name: Run tests
        run: cargo test --verbose
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{runner.os}}-cargo-lint-${{ hashFiles('**/Cargo.toml') }}
      - name: Setup git submodules
        run: git submodule init; git submodule update
      - name: Install alsa, udev, glfw3, sdl, and wayland
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libglfw3-dev libwayland-dev libsdl2-dev
      - name: Run clippy
        run: cargo clippy --workspace --all-targets
      - name: Check format
        run: cargo fmt --all -- --check
